[package]
name = "multithread-samples"
version = "0.1.0"
authors = ["0h-n0 <kbu94982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.25"
